[package]
name = "newsletter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
actix-web = "4"
anyhow = "1.0.69"
config = "0.13.3"
serde = { version = "1.0.156", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
reqwest = { version = "0.11.14", default-features = false, features = ["json"] }
